go.mod
=> Move canonical import path to package-operator.run

config/crds/package-operator.run_clusterobjectsetphases.yaml, config/crds/package-operator.run_clusterobjectsets.yaml, config/crds/package-operator.run_objectsetphases.yaml, config/crds/package-operator.run_objectsets.yaml, config/static-deployment/1-package-operator.run_clusterobjectsetphases.yaml, config/static-deployment/1-package-operator.run_clusterobjectsets.yaml, config/static-deployment/1-package-operator.run_objectsetphases.yaml, config/static-deployment/1-package-operator.run_objectsets.yaml, docs/api-reference.md, magefile.go
=> Fix code-generator lint to ensure generated code is up-to-date

internal/ownerhandling/annotation.go, internal/ownerhandling/annotation_test.go
Signed-off-by: Ankit Kurmi <akurmi@redhat.com>
Added some unit test for functions in `internal/ownerhandling/annotations.go`
=> Added some missing unit test for Package Operator.

cmd/package-operator-manager/main.go, config/examples/nginx/nginx-v1.yaml, config/examples/nginx/nginx-v2.yaml, config/examples/nginx/nginx-v3-broken.yaml, config/examples/nginx/nginx-v4.yaml, config/examples/nginx/nginx-v5.yaml, config/examples/nginx/nginx-v6.yaml, config/examples/nginx/nginx-v7.yaml, go.work.sum, integration/objectsetdeployment_test.go, internal/controllers/objectdeployments/adapter.go, internal/controllers/objectdeployments/adapter_test.go, internal/controllers/objectdeployments/archive_reconciler.go, internal/controllers/objectdeployments/archive_reconciler_test.go, internal/controllers/objectdeployments/hash_reconciler.go, internal/controllers/objectdeployments/mocks.go, internal/controllers/objectdeployments/new_revision_reconciler.go, internal/controllers/objectdeployments/new_revision_reconciler_test.go, internal/controllers/objectdeployments/objectdeployment_controller.go, internal/controllers/objectdeployments/objectset_reconciler.go, internal/controllers/objectdeployments/objectset_reconciler_test.go, internal/utils/hash.go, internal/utils/objectset.go
Implement objectdeployment controller
=> Implement objectsetdeployment controller

internal/controllers/objectdeployments/new_revision_reconciler.go, internal/controllers/objectdeployments/new_revision_reconciler_test.go
Removes dead code and test case covering the now removed extra sanity check in revision reconciler
Signed-off-by: ashish <asnaraya@redhat.com>
=> Remove dead code 

hack/hive/deployment-template.yaml
Signed-off-by: Amador Pahim <apahim@redhat.com>
=> Adding Package Operator base SSS

hack/determine-container-runtime.sh
Signed-off-by: Amador Pahim <apahim@redhat.com>
=> Adding script to find container runtime

config/packages/test-stub/deployment.yaml, config/packages/test-stub/namespace.yaml, internal/packages/adapter_package.go, internal/packages/folderloader.go, internal/packages/folderloader_test.go, internal/packages/folderloadoperation.go, internal/packages/testdata/deployment.yml
=> Make templating context more explicit so templates are easier to understand

hack/hive/deployment-template.yaml
Signed-off-by: Amador Pahim <apahim@redhat.com>
=> Adding real Objects to SSS

config/packages/nginx/deployment.yaml
=> Fix nginx package templating variables

.github/workflows/testing.yaml, magefile.go, sonar-project.properties
=> Add Sonarcloud :)

cmd/kubectl-package/command/build.go, cmd/kubectl-package/command/tree.go, cmd/kubectl-package/command/tree_test.go, cmd/kubectl-package/command/validate.go, internal/packages/packagedeploy/packagedeployer.go, internal/packages/packagestructure/errors.go, internal/packages/packagestructure/validate.go, internal/packages/packagestructure/validate_test.go
=> Add extra validators for labels and GVK

Makefile
=> Add missing images back into internal builds

magefile.go
=> Fix ClusterRole objects not included in PKO Package

magefile.go
=> Use the self-bootstrap-job to install PKO in dev and test

cmd/package-operator-manager/bootstrap.go
When new APIs are introduced the self-bootstrap job created the CRDs without owner references - which is fine when doing a complete fresh installation due to us disabling adoption protection.
But when upgrading an existing cluster, we cannot disable that protection and are stuck not able to rollout PKO.
=> Fix introduction of new APIs blocks self-bootstrap

internal/controllers/objecttemplate/objecttemplate_controller.go
The ObjectTemplate controller was picking up watch results from other watches that use the dynamic cache. This commit limits watch events in for the workqueue to just objects that are watched by ObjectTemplate/ClusterObjectTemplates.
=> Fix ObjectTemplate controller wrongly triggered

apis/core/v1alpha1/clusterobjecttemplate_types.go, apis/core/v1alpha1/zz_generated.deepcopy.go
=> Fix ClusterObjectTemplateList item type

internal/controllers/objectsets/revision_reconciler.go, internal/controllers/objectsets/revision_reconciler_test.go
=> Let revisionReconciler always write revisions

apis/manifests/v1alpha1/packagemanifest_types.go, docs/api-reference.md, internal/packages/packagecontent/tofiles_test.go
make availabilityProbes optional in manifest file
[MTSRE-1213](https://issues.redhat.com//browse/MTSRE-1213)
Bug Fix
=> make availabilityProbes optional in manifest file

.github/workflows/sonar.yaml, .github/workflows/testing.yaml, integration/kubectl-package/helpers_test.go, internal/controllers/objectsetphases/objectsetphase_controller_test.go, magefile.go, sonar-project.properties
Adds integration test results to Sonar analysis
CI
=> ci: add integration coverage results for sonar

go.mod, go.sum, internal/cmd/client.go, internal/cmd/client_test.go, internal/cmd/options.go
Adds client to retrieve in-cluster package related-resources from `kubectl-package`.
New Feature
=> feat: add kube client for kubectl-package

config/packages/package-operator/.test-fixtures/affinity-tolerations-resources/package-operator-manager.Deployment.yaml, config/packages/package-operator/.test-fixtures/no-config/package-operator-manager.Deployment.yaml, config/packages/package-operator/manifest.yaml.tpl, config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl, config/packages/package-operator/trusted-ca-bundle.ConfigMap.yaml.gotmpl
=> Uses environment information to setup Proxy support on OpenShift

internal/environment/environment.go
Ensures proxy key is not present when no proxy options are set.
Bug Fix
=> fix: do not create add proxy key when no proxy config is set

config/packages/package-operator/trusted-ca-bundle.ConfigMap.yaml.gotmpl
Makes package-operator package valid.
Bug Fix
=> fix: add phase annotation to static trusted-ca-bundle configMap

config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl
Updates individual proxy env-vars to may be optional.
Bug Fix
=> Make individual proxy settings optional.

config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl, config/packages/package-operator/trusted-ca-bundle.ConfigMap.yaml.gotmpl
Fix invalid package error when  environment key isn't present. 
Bug Fix
=> Fix environment key

internal/packages/errors.go, internal/packages/packageloader/loader.go, internal/packages/packageloader/loader_test.go, internal/packages/packageloader/validate.go, internal/preflight/empty_namespace_no_default.go
=> add object duplicate validator

.golangci.yaml, internal/cmd/build_test.go, internal/cmd/update.go, internal/controllers/controllers.go, internal/controllers/objectdeployments/adapter_objectset.go, internal/controllers/objectdeployments/adapter_test.go, internal/controllers/phase_reconciler.go, internal/packages/packagecontent/conditionmap.go, internal/packages/packagecontent/totemplate.go, internal/packages/packagedeploy/chunking.go, internal/packages/packagedeploy/deployment_reconciler.go, internal/packages/packageloader/validatefull.go, internal/preflight/preflight.go
=> Enable more Linters

go.work.sum, internal/cli/printer.go
=> Fix linting violation that got through

internal/preflight/dryrun.go, internal/preflight/dryrun_test.go
=> Handle API status error with invalid reason string

OWNERS
Add pbabic to OWNERS
Docs/Test
=> add pbabic to OWNERS

CONTRIBUTING.md
Adds documentation on how to access a kind cluster deployed via the deploy magefile target.
=> Add dev:deploy kind access documentation

config/packages/package-operator/manifest.yaml.tpl, go.mod, go.sum, integration/kubectl-package/kubectl-package_suite_test.go, integration/kubectl-package/testdata/packages/invalid/missing_resource_gvk/deployment.yaml, magefile.go
=> only run cover when go version is greater than 1.20.0

.pre-commit-config.yaml
Bug Fix
JIRA: [MTSRE-994](https://issues.redhat.com/browse/MTSRE-994)
=> [MTSRE-994] Add code generation to pre-commit

cmd/package-operator-manager/components/options.go, cmd/package-operator-manager/components/options_test.go
Duude, point that gun away from my feet! 
Breaking Change
Bug Fix
=> enable leader-election by default

internal/controllers/objectsets/objectsetphases_reconciler.go, internal/controllers/objectsets/objectsetphases_reconciler_test.go
ObjectSetPhases realialized into remote clusters may get stuck reporting in transition, if they contain cluster scoped resources.
This commit fixes this behavior by introducing a fallback lookup that ignores the namespace when checking for in-transition.
Bug Fix
=> Fix remote ObjectSetPhase stuck in transition

cmd/package-operator-manager/bootstrap/bootstrap_test.go, magefile.go
=> Fix unittest not reporting on stdout

cmd/package-operator-manager/bootstrap/init.go, cmd/package-operator-manager/bootstrap/init_test.go, internal/packages/packageimport/registry_test.go
=> Fix upgrade loop on error

magefile.go
=> Update mage deps

cmd/package-operator-manager/main.go
=> Add logr to context of manager

cmd/kubectl-package/versioncmd/version.go, cmd/kubectl-package/versioncmd/version_test.go, cmd/package-operator-manager/components/options.go, cmd/package-operator-manager/main.go, cmd/package-operator-manager/main_test.go, cmd/package-operator-webhook/main.go, cmd/remote-phase-manager/main.go, integration/kubectl-package/version_test.go, internal/version/version.go, internal/version/version_test.go
=> Unify version output

apis/core/v1alpha1/commonpackage_types.go, apis/manifests/v1alpha1/packagemanifest_types.go, config/crds/package-operator.run_clusterpackages.yaml, config/crds/package-operator.run_packages.yaml, config/static-deployment/1-package-operator.run_clusterpackages.yaml, config/static-deployment/1-package-operator.run_packages.yaml, docs/api-reference.md, install.yaml
[https://issues.redhat.com/browse/MTSRE-1344](https://issues.redhat.com/browse/MTSRE-1344)
[https://issues.redhat.com/browse/MTSRE-1345](https://issues.redhat.com/browse/MTSRE-1345)
Added `component` field to (Cluster)Package and and PackageManifest. This is for the planned work on multi-component packages. The component field will instruct PKO on which component to deploy from a multi-component package image.
=> Added component field to Package, PackageManifest

magefile.go
This is in a new PR because prow merged the other PR without waiting for the change request to be closed: https://github.com/package-operator/package-operator/pull/427#discussion_r1305396387
=> retroactively apply PR review suggestion from @kostola

internal/controllers/phase_reconciler.go, internal/controllers/phase_reconciler_test.go
=> Fix owner not patched

cmd/package-operator-manager/bootstrap/proxy/proxy_test.go, go.mod, go.sum, internal/cmd/validate_test.go, internal/controllers/objectdeployments/archive_reconciler_test.go, internal/packages/packagedeploy/deployer.go, internal/packages/packagedeploy/deployer_test.go, internal/utils/imageurl.go, internal/utils/imageurl_test.go, magefiles/config.go
=> Reduce usage of direct dependencies

internal/controllers/phase_reconciler.go, internal/controllers/phase_reconciler_test.go
=> Prevent manager to submit empty patches

internal/controllers/objectsetphases/objectsetphase_controller.go
=> Don't report reconciliation of objectsetphases twice in logs.

.github/CODEOWNERS, .github/dependabot.yml
=> Set eqrx as code owner of go, github actions and dependabot

internal/packages/packagecontent/topackage_multicomponent_test.go, internal/packages/packageloader/loader_test.go, internal/packages/packageloader/testdata/Containerfile, internal/packages/packageloader/testdata/deployment.yml.gotmpl, internal/packages/packageloader/testdata/manifest.yaml
`loader_test.go` doesn't cover the case of a package with a `config` specified in its manifest and, even more, seems to fail when it's added.
This PR aims to fix all the errors and therefore improve coverage.
=> Fix loader_test with config

internal/packages/packagecontent/topackage_multicomponent_test.go
=> Fix multicomponent loading test because file odering is not stable when loading packages

cmd/package-operator-manager/components/options_test.go, internal/controllers/hostedclusters/hostedcluster_controller.go, internal/controllers/hostedclusters/hostedcluster_controller_test.go
=> MTSRE-1520: Fix typo for remote-phase tolerations

internal/packages/packagecontent/topackage.go, internal/packages/violation.go, internal/packages/violation_test.go
=> Add more details to YAML parser error

go.mod, go.sum, integration/kubectl-package/kubectl-package_suite_test.go, magefiles/config.go, magefiles/ns_test_mg.go
=> Remove workarounds for go v1.19

.golangci.yaml, internal/packages/packagecontent/tofiles.go
=> Improve our extensive assorted collection of linters 🎩

integration/package-operator/hypershift_test.go
=> Disable HyperShift Orphaning integration tests

.github/CODEOWNERS
=> Use teams in CODEOWNERS

.github/workflows/testing.yaml
=> Add merge_queue as trigger for gh actions testing pipeline

magefiles/ns_test_mg.go
=> Add ./pkg/... to unit tests

.golangci.yaml, apis/manifests/v1alpha1/packagemanifest_types.go, docs/api-reference.md, magefiles/ns_test_mg.go, pkg/probing/cel.go, pkg/probing/selectors_test.go
=> Run linter in submodules

integration/package-operator/000_upgrade_test.go, integration/package-operator/environment.go, integration/package-operator/hypershift_test.go, integration/package-operator/objectdeployment_test.go, integration/package-operator/objectset_test.go, integration/package-operator/objecttemplate_test.go, integration/package-operator/package_test.go, magefiles/ns_test_mg.go
=> Use build tags to mark integration tests

internal/packages/export_violation.go, internal/packages/internal/packagestructure/conversion.go, internal/packages/internal/packagestructure/manifest.go, internal/packages/internal/packagestructure/manifest_test.go, internal/packages/internal/packagetypes/violation.go
Reduce code-duplication by making the Manifest conversion code generic.
Refactoring
=> Generic Manifest conversion function

.github/workflows/testing.yaml, magefiles/ns_test_mg.go
=> Internalize gotestfmt into mage

apis/core/v1alpha1/clusterobjectset_types.go, apis/core/v1alpha1/clusterobjectsetphase_types.go, apis/core/v1alpha1/clusterobjectslices_types.go, apis/core/v1alpha1/commonobjectset_types.go, apis/core/v1alpha1/objectset_types.go, apis/core/v1alpha1/objectsetphase_types.go, apis/core/v1alpha1/objectslices_types.go, config/crds/package-operator.run_clusterobjectsetphases.yaml, config/crds/package-operator.run_clusterobjectsets.yaml, config/crds/package-operator.run_clusterobjectslices.yaml, config/crds/package-operator.run_objectsetphases.yaml, config/crds/package-operator.run_objectsets.yaml, config/crds/package-operator.run_objectslices.yaml, config/static-deployment/1-package-operator.run_clusterobjectsetphases.yaml, config/static-deployment/1-package-operator.run_clusterobjectsets.yaml, config/static-deployment/1-package-operator.run_clusterobjectslices.yaml, config/static-deployment/1-package-operator.run_objectsetphases.yaml, config/static-deployment/1-package-operator.run_objectsets.yaml, config/static-deployment/1-package-operator.run_objectslices.yaml, docs/api-reference.md, install.yaml
Add CEL transition rules to enforce immutability of immutable fields in objects in the PKO API.
Affected objects:
* (Cluster)ObjectSet
* (Cluster)ObjectSlice
* (Cluster)ObjectSetPhase
New Feature
Immutability of all affected objects has been tested locally.
Jira: [PKO-20](https://issues.redhat.com/browse/PKO-20)
=> [PKO-20] Enforce immutability using CEL

.github/workflows/release.yaml, cmd/build/ci.go
=> [cmd/build] expose crane auth login to CI

.codecov.yaml
Make codecov ignore automatically generated files. Please add any other files that should be ignored.
Docs/Test
=> Make codecov ignore automatically generated files

README.md
update link to the website
-- Docs/Test --
Signed-off-by: Brady Pratt <bpratt@redhat.com>
=> fix link to website repository

.codecov.yaml
=> [codecov] ignore cmd/build because our build code does not have integration tests

cmd/build/generate.go
=> [cmd/build] reintroduce accidentally dropped conversion-gen calls

cmd/package-operator-manager/components/options_test.go, internal/packages/internal/packagestructure/manifest_test.go
=> make linter happy

.codecov.yaml
Exclude untestable code from our coverage statistics.
Bug Fix
=> [PKO-78] [ci/codecov] ignore coverage for cmd/build and cmd/test-stub

.github/workflows/testing.yaml
=> [ci/testing] only fail ci on failed code coverage upload when not in PR

internal/packages/internal/packagevalidation/validation.go, internal/packages/internal/packagevalidation/validation_test.go
=> [PKO-83] Fix PackageScopeValidator

integration/package-operator/helpers_test.go, integration/package-operator/package_test.go
This PR
- changes the signature of `testNamespacedAndCluster`'s postCheck arg to pass the namespace as a string instead of only a boolean (empty string == not namespaced)
- adds `assertAmountOfSliceObjectsControlledPerObjectSet` test helper which attributes (Cluster)ObjectSlices to their controlling (Cluster)ObjectSet via owner references
- changes `TestPackage_simpleWithSlices` and `TestPackage_simpleWithoutSlices` to use `assertAmountOfSliceObjectsControlledPerObjectSet`.
Bug Fix
=> [integration] bugfix for PKO-85: correctly attribute (Cluster)ObjectSlices to their owning (Cluster)ObjectSets

cmd/kubectl-package/buildcmd/build.go, cmd/kubectl-package/buildcmd/build_test.go, integration/kubectl-package/build_test.go
Print affirmative message for successful package build
Jira: [PKO-104](https://issues.redhat.com/browse/PKO-104)
=> feat: [PKO-104] Print affirmative message for successful package build

config/.gitignore, config/deploy/webhook/deployment.yaml.tpl, config/images/cli.Containerfile, config/images/package-operator-manager.Containerfile, config/images/package-operator-webhook.Containerfile, config/images/remote-phase-manager.Containerfile, config/images/test-stub.Containerfile, config/packages/package-operator/.gitignore, config/packages/package-operator/.test-fixtures/affinity-tolerations-resources/package-operator-manager.Deployment.yaml, config/packages/package-operator/.test-fixtures/affinity-tolerations-resources/package-operator.Namespace.yaml, config/packages/package-operator/.test-fixtures/no-config/package-operator-manager.Deployment.yaml, config/packages/package-operator/.test-fixtures/no-config/package-operator.Namespace.yaml, config/packages/package-operator/.test-fixtures/openshift-with-proxy/package-operator-manager.Deployment.yaml, config/packages/package-operator/.test-fixtures/openshift-with-proxy/package-operator.Namespace.yaml, config/packages/package-operator/components/hosted-cluster/.test-fixtures/with-config/package-operator-manager.Deployment.yaml, config/packages/package-operator/components/hosted-cluster/.test-fixtures/with-config/package-operator.Namespace.yaml, config/packages/package-operator/components/hosted-cluster/.test-fixtures/without-config/package-operator-manager.Deployment.yaml, config/packages/package-operator/components/hosted-cluster/.test-fixtures/without-config/package-operator.Namespace.yaml, config/packages/package-operator/components/hosted-cluster/package-operator-manager.Deployment.yaml.gotmpl, config/packages/package-operator/components/hosted-cluster/package-operator.Namespace.yaml.gotmpl, config/packages/package-operator/components/remote-phase/.gitignore, config/packages/package-operator/components/remote-phase/.test-fixtures/affinity-tolerations-resources/package-operator-remote-phase-manager.Deployment.yaml, config/packages/package-operator/components/remote-phase/.test-fixtures/namespace-scope/package-operator-remote-phase-manager.Deployment.yaml, config/packages/package-operator/components/remote-phase/package-operator-remote-phase-manager.Deployment.yaml.gotmpl, config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl, config/packages/package-operator/package-operator.Namespace.yaml.gotmpl, config/remote-phase-static-deployment/deployment.yaml.tpl, config/self-bootstrap-job.yaml.tpl, config/static-deployment/deployment.yaml.tpl, integration/package-operator/restrictedpolicy_test.go
this resolves https://issues.redhat.com/browse/PKO-37
=> PKO-37 - Comply with restricted PSA enforcement

internal/packages/internal/packagerender/objectsettemplate.go
=> Drop CEL annotation from render

cmd/kubectl-package/repocmd/repo_test.go, go.mod, internal/packages/internal/packagemanifestvalidation/repository_test.go, internal/packages/internal/packagerepository/multirepositoryindex_test.go, internal/packages/internal/packagerepository/repositoryindex.go, internal/packages/internal/packagerepository/repositoryindex_test.go, internal/packages/internal/packageresolving/repo_test.go, internal/packages/internal/packageresolving/testdata/.gitignore, internal/packages/internal/packagestructure/manifest_test.go
Package Repository tests
Tests
=> Package Repository tests

internal/packages/internal/packagekickstart/presets/phases.go
=> Fix RoleBindings kickstarted to wrong phase

cmd/package-operator-manager/bootstrap/apihelper_test.go, cmd/package-operator-manager/components/components_test.go, cmd/package-operator-manager/components/options_test.go, internal/adapters/objectdeployment_test.go, internal/adapters/objectslice_test.go, internal/adapters/package_test.go
=> Added missing unit tests for manager and adapters

internal/controllers/objectdeployments/hash_reconciler_test.go, internal/controllers/objectdeployments/mocks_test.go, internal/controllers/objectdeployments/objectdeployment_controller_test.go, internal/controllers/objecttemplate/errors_test.go
=> Added unit tests for reconcilers

cmd/kubectl-package/updatecmd/update.go, cmd/kubectl-package/updatecmd/update_test.go
=> Added affirmative message for succesfull package update

cmd/package-operator-manager/components/components.go, cmd/package-operator-manager/components/repository.go, cmd/package-operator-manager/components/setups.go, cmd/package-operator-manager/components/setups_test.go, internal/adapters/repository.go, internal/adapters/repository_test.go, internal/controllers/repositories/repository_controller.go, internal/packages/export_repository.go
Second PR part of the split of #1413 
This one adds the boilerplate code for the Repository and ClusterRepository controller.
New Feature
=> Add Repository/ClusterRepository controller boilerplate

internal/packages/internal/packageimport/registry.go
=> Remove pull option that makes pko skip tls validation.

.github/dependabot.yml
Jira: https://issues.redhat.com/browse/PKO-200
Group modules with import path `k8s.io/*` into a combined dependabot upgrade PRs.
Build/Updates
standard.
=> PKO-200 - build(dependabot): group kubernetes dependencies together

CONTRIBUTING.md
Browsing through this file in our refinement made me realize that the documented entrypoints where slightly outdated and missing an explanation of the IMAGE_REGISTRY override.
Docs/Test
standard.
Preview link to the changed markdown file: https://github.com/erdii/package-operator/blob/update-developer-documentation/CONTRIBUTING.md
=> docs: refresh dev entrypoints in CONTRIBUTING.md

config/packages/package-operator/.test-fixtures/affinity-tolerations-resources/package-operator-manager.Deployment.yaml, config/packages/package-operator/.test-fixtures/no-config/package-operator-manager.Deployment.yaml, config/packages/package-operator/.test-fixtures/openshift-with-proxy/package-operator-manager.Deployment.yaml, config/packages/package-operator/.test-fixtures/root-affinity-tolerations-resources/package-operator-manager.Deployment.yaml, config/packages/package-operator/components/hosted-cluster/.test-fixtures/with-config/package-operator-manager.Deployment.yaml, config/packages/package-operator/components/hosted-cluster/.test-fixtures/without-config/package-operator-manager.Deployment.yaml, config/packages/package-operator/components/hosted-cluster/package-operator-manager.Deployment.yaml.gotmpl, config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl, config/static-deployment/deployment.yaml.tpl
This change removes all references/declarations to the unused envvar "PKO_IMAGE"
Cleanup
=> Remove all references to unused envvar PKO_IMAGE

cmd/build/ci.go, cmd/build/dev.go, cmd/build/lint.go, cmd/build/main.go
=> build(cardboard): add govulncheck step to ci:postpush, dev:precommit and as standalone target dev:govulncheck

.github/dependabot.yml
Added `build(deps)` prefix to dependabot PRs. This will make filtering PRs and notifications easier. 
standard.
=> Added build(deps) prefix to dependabot PRs

.golangci.yaml, cmd/package-operator-manager/components/components.go, cmd/remote-phase-manager/main.go
inspired by:
- https://github.com/operator-framework/catalogd/pull/519
- https://github.com/operator-framework/operator-controller/pull/1663
Bug Fix
standard.
=> fix: Set recommended leaderelection settings

.github/workflows/release.yaml, .github/workflows/testing.yaml
We need to be compatible with it
=> Pin gh actions go version to 1.23

cmd/kubectl-package/pausecmd/pause.go, internal/cmd/pause.go, internal/cmd/pause_test.go
Fix the pause CLI to work with ClusterPackages.
Bug Fix
standard.
=> Fix the pause CLI to work with ClusterPackages

cmd/package-operator-manager/components/components_test.go
Create a temporary empty file and point the KUBECONFIG envvar to it because it can otherwise pick up a valid kubeconfig from ~/.kube/config, which makes the test fail.
This had just happened to me:
```
=== RUN   TestProvideRestConfig
components_test.go:42: 
Error Trace:	/home/erdii/projects/redhat/github.com/package-operator/package-operator/cmd/package-operator-manager/components/components_test.go:42
Error:      	An error is expected but got nil.
Test:       	TestProvideRestConfig
--- FAIL: TestProvideRestConfig (0.01s)
```
standard.
=> fix(tests): create temporary empty kubeconfig for TestProvideRestConfig

internal/cmd/pause_test.go
Prevent race conditions in unit tests in `pause_test.go`.
Jira: [PKO-250](https://issues.redhat.com/browse/PKO-250)
Bug Fix
standard.
=> [PKO-250] Fix race conditions

cmd/build/test.go
Reduce output generated from testing
Docs
standard.
=> [PKO-230] Reduce gotestfmt output msgs

cmd/build/dev.go
=> fix(cmd/build): fix precommit racyness by running code generators before linters and other tasks)

internal/controllers/packages/package_controller.go, internal/controllers/packages/unpack_reconciler.go, internal/controllers/packages/unpack_reconciler_test.go, internal/packages/internal/packagedeploy/deployer.go
=> fix error handling in unpackReconciler and packageDeployer

.golangci.yaml, cmd/package-operator-manager/bootstrap/fix_test.go, cmd/package-operator-manager/bootstrap/proxy/proxy_test.go, integration/package-operator/environment.go, integration/package-operator/objectdeployment_test.go, internal/controllers/objectdeployments/archive_reconciler_test.go, internal/controllers/objectdeployments/new_revision_reconciler.go, internal/controllers/objectdeployments/new_revision_reconciler_test.go, internal/controllers/objectdeployments/objectset_reconciler_test.go, internal/controllers/objectsetphases/objectsetphase_reconciler.go, internal/controllers/objectsetphases/objectsetphase_reconciler_test.go, internal/controllers/packages/unpack_reconciler.go, internal/controllers/phase_reconciler.go, internal/controllers/phase_reconciler_test.go, internal/packages/internal/packageimport/kubekeychain/kubekeychain_test.go, internal/packages/internal/packagestructure/structure.go, internal/packages/internal/packagevalidation/kubeconform.go, internal/packages/internal/packagevalidation/kubeconform_test.go, internal/packages/internal/packagevalidation/templatevalidation.go
Created on the refinement hour of the 24.03.25
=> Enable unparam linter

.github/workflows/testing.yaml
=> fix: pa token passing in update-go-modules job

.github/workflows/testing.yaml
=> fix: pat passing in testing/update-go-modules

.github/workflows/testing.yaml
(we're getting desperate)
standard.
=> fix: try passing the PAT in the envvar GITHUB_TOKEN

.github/workflows/testing.yaml
=> fix(testing/update-go-modules): define a  credential helper to pass the token

.github/workflows/testing.yaml
=> chore(testing/update-go-modules): drop PAT from commit step environment variables

cmd/build/ci.go
This commit removes uploading test-stubs to repositories
Fix / Cleanup
standard.
Addresses PKO-227
=> [PKO-227] Remove test stub images

apis/core/v1alpha1/clusterobjectdeployment_types.go, apis/core/v1alpha1/clusterobjectset_types.go, apis/core/v1alpha1/commonobjecttemplate_types.go, apis/core/v1alpha1/commonpackage_types.go, apis/core/v1alpha1/objectdeployment_types.go, apis/core/v1alpha1/objectset_types.go, cmd/build/main.go, docs/api-reference.md
=> Update docgen and add examples

CONTRIBUTING.md, cmd/build/bootstrap.go, cmd/build/dev.go, cmd/build/test.go
this prepares a dev cluster and installs pko in it
expose cluster setup + pko bootstrap via `./do dev:bootstrap`
Dev Feature
standard.
=> chore: expose dev cluster pko bootstrap via `./do dev:bootstrap`

cmd/build/cluster.go, cmd/build/generate.go, cmd/build/image.go, cmd/build/package.go, cmd/build/test.go, config/packages/test-stub-image-prefix-override/.gitignore, config/packages/test-stub-image-prefix-override/deployment.yaml.gotmpl, config/packages/test-stub-image-prefix-override/manifest.yaml.tpl, config/self-bootstrap-job.yaml.tpl, integration/package-operator/environment.go, integration/package-operator/image_prefix_override_test.go, internal/packages/internal/packagedeploy/deployer.go
Added an integration test for the image prefix override feature. The test verifies the image has been mirrored for both package and workload images. 
Test
standard.
=> PKO-264: Image prefix override integration test

go.mod, go.sum, internal/testutil/managedcachemocks/accessor.go
manual update since boxcutter v0.1.3 introduces breaking changes
=> deps: update boxcutter to 0.1.2

go.mod, go.sum, internal/testutil/managedcachemocks/accessor.go, pkg/go.mod, pkg/go.sum
=> Bump Boxcutter to v0.5.2

cmd/package-operator-manager/components/cachemanager.go
=> chore: rename ctrlmetrics import for consistency

apis/core/v1alpha1/clusterobjectset_types.go, apis/core/v1alpha1/objectset_types.go, config/crds/package-operator.run_clusterobjectsets.yaml, config/crds/package-operator.run_objectsets.yaml, config/static-deployment/1-package-operator.run_clusterobjectsets.yaml, config/static-deployment/1-package-operator.run_objectsets.yaml, docs/api-reference.md, integration/package-operator/objectset_test.go, internal/controllers/objectdeployments/archive_reconciler_test.go, internal/controllers/objectdeployments/objectset_reconciler.go, internal/controllers/objectsets/objectset_controller.go, internal/controllers/objectsets/revision_reconciler_test.go
=> [PKO-318] Fix os revisions
