README.md
If `CONTAINER_RUNTIME` is undefined you will get messages like:
```
package-operator main $ bin/mage dev:setup
2022/09/26 15:18:45 "level"=0 "msg"="detected container-runtime" "container-runtime"="podman"
Error: initializing dev environment: getting existing kind clusters: exit status 1
```
This might send you off debugging in the wrong direction.
Adds a dev note to the README to alert dev users to define this env variable
=> Notes need to define CONTAINER_RUNTIME

apis/core/v1alpha1/commonobjectset_types.go, integration/objectset_test.go, internal/controllers/objectsets/objectsetphases_reconciler.go
InTransition is set while an ObjectSet is not rolled out completely. This condition prevents ambeguity when looking at ObjectSet objects during an rollout process.
If an ObjectSet is InTransition, we will delay to report Succeeded until the rollout state is clean.
=> Introduce InTransition condition

cmd/package-operator-manager/main.go, internal/controllers/objectsetphases/objectsetphase_controller.go, internal/controllers/objectsets/objectset_controller.go, internal/controllers/phase_reconciler.go, internal/preflight/apis_exist.go, internal/preflight/namespace_escalation_protection.go, internal/preflight/preflight.go
Introduced preflight checks ensure that users can't escalate their permissions by creating objects in other namespaces or cluster scoped when using namespace-scoped APIs.
A second preflight check ensures that APIs are registered in the cluster before attempting to create objects.
=> Implement preflight checks

integration/objectdeployment_test.go, integration/objectset_test.go, internal/controllers/objectdeployments/adapter_objectset.go, internal/controllers/objectdeployments/archive_reconciler_test.go, internal/controllers/objectdeployments/new_revision_reconciler.go, internal/controllers/objectdeployments/new_revision_reconciler_test.go, internal/controllers/objectdeployments/objectdeployment_controller.go, internal/controllers/objectdeployments/objectset_reconciler.go, internal/controllers/objectdeployments/objectset_reconciler_test.go
Remove ObjectDeploymentRevision annotation and rely on revision count reporting from ObjectSets.
Previously ObjectDeployment.metadata.generation was used to track the latest ObjectSet revision number, but .metadata.generation will diverge from the revision generation counter if fields outside the .spec.template.spec (e.g. RevisionHistoryLimit) are changed.
This PR is also closing a few different race conditions that come from using only inaccurate timestamps for revision ordering or not waiting for all ObjectSets to report a revision number.
=> Remove ObjectDeployment revision annotation

.gitignore, cmd/package-operator-manager/bootstrap.go, cmd/package-operator-manager/main.go, config/packages/package-operator/.gitignore, config/packages/package-operator/README.md, config/packages/package-operator/crds/clusterobjectdeployments.package-operator.run.CustomResourceDefinition.yaml, config/packages/package-operator/crds/clusterobjectsetphases.package-operator.run.CustomResourceDefinition.yaml, config/packages/package-operator/crds/clusterobjectsets.package-operator.run.CustomResourceDefinition.yaml, config/packages/package-operator/crds/clusterpackages.package-operator.run.CustomResourceDefinition.yaml, config/packages/package-operator/crds/objectdeployments.package-operator.run.CustomResourceDefinition.yaml, config/packages/package-operator/crds/objectsetphases.package-operator.run.CustomResourceDefinition.yaml, config/packages/package-operator/crds/objectsets.package-operator.run.CustomResourceDefinition.yaml, config/packages/package-operator/crds/packages.package-operator.run.CustomResourceDefinition.yaml, config/packages/package-operator/manifest.yaml, config/packages/package-operator/package-operator-system.Namespace.yaml, config/packages/package-operator/rbac/package-operator.ClusterRoleBinding.yaml, config/packages/package-operator/rbac/package-operator.Role.yaml, config/packages/package-operator/rbac/package-operator.RoleBinding.yaml, config/packages/package-operator/rbac/package-operator.ServiceAccount.yaml, config/self-bootstrap-job.yaml, internal/controllers/phase_reconciler.go, internal/packages/folderloadoperation.go, magefile.go
Implement capability to let PKO install itself from a Package.
Still needs some polish.
To check it out:
```sh
./mage dev:teardown
./mage dev:setup
./mage dev:load
vim config/self-bootstrap-job.yaml
kubectl create -f config/self-bootstrap-job.yaml
kubectl get clusterpackage
NAME               STATUS      AGE
package-operator   Available   9m32s
```
=> Implement PKO self-bootstrap

.github/workflows/sonar.yaml, .github/workflows/testing.yaml
The SONAR_TOKEN secret is not exposed when opening a PR from a fork, making all external PRs fail. To workaround this issue, we are now executing the Sonar workflow from main, which has access to the Secrets :).
=> Move SonarCloud into it's own workflow

magefile.go
=> Raise an error message when running ./mage deploy without VERSION env

.github/workflows/release.yaml, magefile.go
Let GH release action attach cli multi arch binaries to the created release.
This requires mage to name binaries as how they are supposed to show up in the release.
=> Cli binary attached to releases

cmd/kubectl-package/command/command.go, cmd/kubectl-package/command/tree.go, cmd/kubectl-package/command/tree_test.go, go.mod, go.sum
Introducing a tree command to quickly see the logical structure of a package after templating and assembly into phases.
Example Outputs
```
$ go run ./cmd/kubectl-package tree ./config/packages/test-stub          
Package <namespace>/<name>
└── Phase deploy
└── apps/v1, Kind=Deployment /test-stub-<name>
$ go run ./cmd/kubectl-package tree ./config/packages/test-stub --cluster
ClusterPackage /<name>
└── Phase namespace
└── /v1, Kind=Namespace /<name>
└── Phase deploy
└── apps/v1, Kind=Deployment <name>/test-stub-<name>
$ go run ./cmd/kubectl-package tree ./config/packages/test-stub --cluster
Error: loading package contents: Package validation errors:
- Missing package-operator.run/phase Annotation in deployment.yaml#0
```
=> Implement tree command to inspect package contents

internal/controllers/phase_reconciler.go, internal/controllers/phase_reconciler_test.go
Change object patching behaviour to strategic merge to better support mutating integrations and better conform to our documentation about "if you don't specify a field, PKO won't touch it"
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#notes-on-the-strategic-merge-patch
=> Use strategic merge strategy

go.mod, go.sum, magefile.go
This PR removes generic image building and pushing functionality from `magefile.go` and uses functions provided by DevKube instead (added by this PR: [#23](https://github.com/mt-sre/devkube/pull/23)).
[MTSRE-777](https://issues.redhat.com/browse/MTSRE-777)
=> Move image building and pushing functionality to DevKube

apis/core/v1alpha1/clusterobjectsetphase_types.go, apis/core/v1alpha1/objectsetphase_types.go, config/crds/package-operator.run_clusterobjectsetphases.yaml, config/crds/package-operator.run_objectsetphases.yaml, config/static-deployment/1-package-operator.run_clusterobjectsetphases.yaml, config/static-deployment/1-package-operator.run_objectsetphases.yaml, config/static-deployment/20-rbac.yaml, docs/api-reference.md, install.yaml, integration/hypershift_test.go, integration/objectset_test.go, internal/controllers/objectsetphases/objectsetphase_controller.go, internal/controllers/phase_reconciler.go, internal/controllers/phase_reconciler_test.go, internal/ownerhandling/annotation.go, internal/ownerhandling/annotation_test.go, internal/ownerhandling/common.go, internal/ownerhandling/native.go, internal/ownerhandling/native_test.go, internal/testutil/ownerhandlingmocks/ownerstrategy_mock.go
The remote phase manager lacked permissions to access ObjectSet APIs. This access is required to lookup previous revisions to feed the adoption checker that prevents us from working on objects already under ownership of other Packages or controllers.
During fixing this bug, I've also found that the integration tests that should have prevented this issue are not executed correctly skipping the remote-phase manager.
With the problems in the integration test suite patched, we can be sure that regressions are detected in the future :)
=> Remote Phase Manager lacks ObjectSet permissions

config/remote-phase-static-deployment/2-secret.yaml.tpl, config/remote-phase-static-deployment/deployment.yaml.tpl, integration/hypershift_test.go, magefile.go
Use service-network kubeconfig in HyperShift to use internal network connectivity and don't access HostedCluster kube-apiservers using external LoadBalancers.
=> Use service-network kubeconfig in HyperShift

.github/dependabot.yml, .github/workflows/update.yaml, .gitignore, go.work.sum
Dependabots has problems with go workspaces and creates broken PRs. This commit creates a scheduled workflow that runs `go get` appropriately and actually cleans up.
=> Use custom workflow for go updates

cmd/package-operator-manager/components/components.go, cmd/remote-phase-manager/main.go
In large clusters with many APIs, PKO startup may take a long time because we are running into client throttling.
Switch to lazy restmapper to delay apidiscovery until required.
=> Use lazy rest mapper

go.work.sum, internal/controllers/objecttemplate/template_reconciler.go, internal/controllers/objecttemplate/template_reconciler_test.go
Support full jsonpath spec for ObjecTemplate sources, allowing ranges filters, map-key access and more:
https://kubernetes.io/docs/reference/kubectl/jsonpath/
=> Support jsonpath spec for ObjectTemplate sources

internal/controllers/objecttemplate/template_reconciler.go, magefile.go
Rendered object preflight errors weren't being shown in the conditions because they weren't wrapped in a SourceError
=> Wrap preflight violations in SourceError

internal/controllers/config.go, internal/controllers/errors.go, internal/controllers/errors_test.go, internal/controllers/objectsetphases/objectsetphase_reconciler.go, internal/controllers/objectsetphases/objectsetphase_reconciler_test.go, internal/controllers/objectsets/objectsetphases_reconciler.go, internal/controllers/objectsets/objectsetphases_reconciler_test.go, internal/controllers/options.go, internal/controllers/packages/unpack_reconciler.go, internal/controllers/packages/unpack_reconciler_test.go, internal/controllers/phase_reconciler.go
Applies backoff when external objects are not found for a given phase reconciliation loop.
This is needed to prevent "hot" loops from occurring due to external issues.
=> [MTSRE-1142] fix: apply backoff when external objects not found

internal/preflight/dryrun.go, internal/preflight/dryrun_test.go
Performing a dry-run on an object may mutate the object using webhooks or API-internal defaulting. Trying to create this object afterwards may not succeed.
=> DryRun preflight check mutates object

internal/packages/packageimport/fs.go, internal/packages/packageimport/image.go, internal/packages/packageimport/image_test.go
Package operator is ignoring hidden "dot" files when loading and building package images.
So when consuming a PKO-CLI-build package image, all dot files will be already stripped.
But when importing a package image that has been build with docker/podman and still contains dot-files, we are loading them into the ObjectDeployment.
This commit strips all dot files/paths when importing image contents.
Bug Fix
=> Fix hidden files imported from image

cmd/kubectl-package/updatecmd/update.go, internal/cmd/update.go, internal/cmd/update_test.go
Running kubectl-package update on an empty lockfile will clear the content of the lockfile making package validation for subsequent calls fail.
Bug Fix
=> Hotfix 2nd kubectl-package update empties lockfile

apis/manifests/v1alpha1/packagemanifest_types.go, internal/controllers/controllers.go, internal/controllers/objectdeployments/new_revision_reconciler.go, internal/controllers/objectdeployments/objectdeployment_controller.go, internal/packages/packagedeploy/deployer.go, internal/packages/packagedeploy/deployment_reconciler.go, internal/packages/packagedeploy/deployment_reconciler_test.go
- Add a object-deployment label to ObjectSets to query deployment childs
- Add change cause annotation taken from kube Deployments
- Add source-image and config annotations to ObjectDeployments and ObjectSets to refer back to the originating Package
New Feature
=> Prepares PKO for rollback CLI commands

config/packages/package-operator/.test-fixtures/affinity-tolerations-resources/package-operator.Namespace.yaml, config/packages/package-operator/.test-fixtures/no-config/package-operator.Namespace.yaml, config/packages/package-operator/.test-fixtures/openshift-with-proxy/package-operator.Namespace.yaml, config/packages/package-operator/package-operator.Namespace.yaml.gotmpl
This sets pod security admission labels. Currently, none are set and starting with OpenShift 4.13 this generates warnings in Telemetry. This fixes it.
Refer to https://kubernetes.io/docs/concepts/security/pod-security-standards/ to further tighten the labels potentially to the recommended `restricted` level.
Bug Fix
=> [AUTH-388] config/packages/p/namespace.yaml: set pod security admission labels

internal/packages/packagecontent/content.go, internal/packages/packagecontent/content_test.go, internal/packages/packageimport/registry.go, internal/packages/packageimport/registry_test.go
Loading the same package image for multiple packages in parallel is de-duplicated, but the resulting data structure is afterwards manipulated by multiple go routines in parallel.
This fix is always returning a DeepCopy of the File map to prevent this data race.
Bug Fix
=> [MTSRE-1300] Fix data race when Packages are loaded in parallel

config/images/package.Containerfile, magefile.go
* delete unused `package.Containerfile`
* found when working on [MTSRE-1308](https://issues.redhat.com/browse/MTSRE-1308)
=> delete unused Containerfile

cmd/package-operator-manager/components/options.go, cmd/package-operator-manager/components/options_test.go, cmd/package-operator-manager/components/package.go, config/packages/package-operator/manifest.yaml.tpl, config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl, internal/adapters/package.go, internal/controllers/packages/package_controller.go, internal/controllers/packages/unpack_reconciler.go, internal/controllers/packages/unpack_reconciler_test.go
https://issues.redhat.com/browse/MTSRE-1391
This PR adds a parameter to package operator that allows adding a value used for the generated unpacked package hash. 
This parameter enables us to force a re-deployment of all packages.
New Feature
=> [MTSRE-1391] Allow force re-deployment of all packages

internal/controllers/objectdeployments/archive_reconciler.go, internal/controllers/objectdeployments/archive_reconciler_test.go, internal/controllers/previous_revision_lookup.go
Currently archived `objectsets` are not being garbage collected according to the `revisionHistoryLimit`. This PR fix this bug so when new revisions are created archived ones are deleted accordingly. `objectsets` are also configured to only store the same number of `previousRevisions` to avoid 'not found' errors when looking up previous revisoins which have been garbage collected. 
Bug Fix
=> [MTSRE-1277] Fix garbage collection of archived revisions

internal/controllers/objectdeployments/new_revision_reconciler.go, internal/controllers/objectdeployments/new_revision_reconciler_test.go, internal/controllers/objectdeployments/objectset_reconciler_test.go
Archived ObjectSets need to trigger the hash collision detector to allow users to rollback to previously archived revisions.
Bug Fix
=> Archived revisions not incrementing hash collision

internal/controllers/config.go, internal/controllers/objectsetphases/objectsetphase_adapter.go, internal/controllers/objectsetphases/objectsetphase_controller.go, internal/controllers/objectsetphases/objectsetphase_controller_test.go, internal/controllers/objectsets/adapter_objectset.go, internal/controllers/objectsets/objectset_controller.go, internal/controllers/objectsets/objectset_controller_test.go, internal/controllers/phase_reconciler.go, internal/controllers/phase_reconciler_test.go
Collision detetor errors, like "adoption refused" where only logged and where not apperant to the user in the API. This commit adds this reporting.
Bug Fix
=> Report Collision Detection Errors into API

config/packages/remote-phase/.test-fixtures/namespace-scope/package-operator-remote-phase-manager.Deployment.yaml, config/packages/remote-phase/package-operator-remote-phase-manager.Deployment.yaml.gotmpl
Adds labels to allow network access within the HyperShift environment.
Bug Fix
=> Set hypershift isolation label

.gitignore, cmd/package-operator-manager/bootstrap/bootstrap.go, cmd/package-operator-manager/bootstrap/bootstrap_test.go, cmd/package-operator-manager/bootstrap/fix.go, cmd/package-operator-manager/bootstrap/fix/1.7.0_crd-pluralization.go, cmd/package-operator-manager/bootstrap/fix/1.7.0_crd-pluralization_test.go, cmd/package-operator-manager/bootstrap/fix/scheme_test.go, cmd/package-operator-manager/bootstrap/fix/types.go, cmd/package-operator-manager/bootstrap/fix_test.go
This fix cleans up the singular version of two pluralized CRDs and resolves [MTSRE-1379](https://issues.redhat.com//browse/MTSRE-1379) in our internal bugtracker.
An upgrade [1] to the controller-runtime dependency also upgraded the code generators that generate our CustomResourceDefinition manifests from the apis package. This upgrade fixed a pluralization library used in the generators, which in turn 'fixed' the `plural` names of the CRDs `ClusterObjectSlices` and `ObjectSlices` and appended a missing 's' to both names.
- `objectslice` -> `objectslices`
- `clusterobjectslice` -> `clusterobjectslices`
Upgrading from an existing PKO installation with the old (singular) CRDs in place to a new version with the new (pluralized) CRDs results in a broken state because the old singular CRDs …
=> MTSRE-1379 fix duplicate CRDs in self-bootstrap-job

config/self-bootstrap-job.yaml.tpl, magefile.go
test using 
```bash
./mage dev:teardown
IMAGE_ORG=eef-freef.io/sbubby ./mage dev:deploy
export KUBECONFIG=$PWD/.cache/dev-env/kubeconfig.yaml
kubectl get deployment -n package-operator-system package-operator-manager -o yaml \
| yq '.spec.template.spec.containers[0].image'
```
=> make (default)ImageOrg in magefile truly configurable

cmd/package-operator-manager/bootstrap/bootstrap.go, cmd/package-operator-manager/bootstrap/proxy/proxy.go, cmd/package-operator-manager/bootstrap/proxy/proxy_test.go, go.mod
Go caches proxy settings that are read from the envvars `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY. This means that our bootstrap procedure:
1. detect if running in kube or openshift
2. (in openshift) detect if cluster proxy settings are configured and override bootstrap process proxy environment variables
3. assume that from now on all http/https calls that are not excluded via `NO_PROXY` will go through the configured proxy
will not work because the calls to the kubernetes api have already read and cached the envvars in go code.
The workaround is:
- lookup proxy settings from cluster and environment variables
- if they are different: merge proxy settings into environment variables and replace current pko process with a new instance by using unix.Exec (execve)
Bug Fix
=> MTSRE-1454 fix HTTP(S) proxy configuration coming from in-cluster objects

config/examples/packages/test-stub.yaml, integration/package-operator/hypershift_test.go
This refactoring should make it easier to re-run HyperShift specific tests, because it is no longer producing an error if the hostedcluster CRD is already installed.
A command like this to just run the test you are interested in: ./mage test:packageoperatorintegrationrun
TestHyperShift/ObjectSetOrphanCascadeDeletion
=> Refactor HyperShift integration tests for re-run

internal/environment/environment.go
Cancelling the manager context resulted in a failed shutdown because the environment manager runnable did not stop within the shutdown deadline of 30 seconds.
I refactored the re-probe ticker code to respect context cancelling.
Now the bootstrapper will properly shut down when the installed PKO becomes available.
Bug Fix
=> [MTSRE-1426] Fix bootstrap controller shutdown when context is cancelled

internal/packages/packageloader/loader_test.go, internal/packages/packageloader/package_files_template_transformer.go, internal/packages/packageloader/testdata/_helpers.gotmpl, internal/packages/packageloader/testdata/deployment.yml.gotmpl, internal/transform/transformfiles_funcs.go, internal/transform/transformfiles_funcs_test.go
This commit adds the include template helper function to evaluate template blocks into a string. This helper can be used to pipe the output of a template into other functions for manipulation.
New Feature
=> MTSRE-1504: Add include template function

cmd/remote-phase-manager/main.go, internal/controllers/objectsetphases/objectsetphase_controller.go, internal/controllers/objectsetphases/objectsetphase_reconciler.go, internal/controllers/objectsets/objectset_controller.go, internal/controllers/objectsets/remotephase_reconciler.go, internal/controllers/objectsets/remotephase_reconciler_test.go, internal/controllers/phase_reconciler.go, internal/controllers/phase_reconciler_test.go, internal/testutil/ownerhandlingmocks/ownerstrategy_mock.go
Our integration tests have a flake in `TestHyperShift/ObjectSetOrphanCascadeDeletion`, that particularly manifests when PKO is running with very limited cpu resources.
This is the error:
```
hypershift_test.go:94: 
Error Trace:	/home/runner/work/package-operator/package-operator/integration/package-operator/objectset_test.go:655
/home/runner/work/package-operator/package-operator/integration/package-operator/objectset_test.go:718
/home/runner/work/package-operator/package-operator/integration/package-operator/hypershift_test.go:94
Error:      	Received unexpected error:
configmaps "cm" not found
Test:       	TestHyperShift/ObjectSetOrphanCascadeDeletion
--- FAIL: TestHyperShift (54.66s)
--- PASS: TestHyperShift/HyperShift_Installation (1.28s)
--- PASS: …
```
=> [MTSRE-1471] Fix orphaning of objects owned by (Cluster)ObjectSets and their phases

cmd/package-operator-manager/components/hostedcluster.go, cmd/package-operator-manager/components/options.go, config/examples/packages/test-stub.yaml, config/packages/package-operator/.test-fixtures/affinity-tolerations-resources/package-operator-manager.Deployment.yaml, config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl, config/packages/remote-phase/manifest.yaml.tpl, config/packages/remote-phase/package-operator-remote-phase-manager.Deployment.yaml.gotmpl, internal/controllers/hostedclusters/hostedcluster_controller.go, internal/controllers/hostedclusters/hostedcluster_controller_test.go
The remote-phase-manger is not affected by affinity and toleration settings given to the main package.
This commit ensures that affinity and tolerations that are set for the main package-operator-manager also affect the remote-phase-manager.
=> MTSRE-1520: Enable PKO sub-component affinity and toleration

internal/packages/packagecontent/topackage.go, internal/packages/packageloader/loader_test.go, internal/packages/packageloader/testdata/deployment.yml.gotmpl
When loading YAML files, we did blindly split on ---, so if someone added a PEM encoded certificate that is using ------ add start/end, we where splitting the document...
This commit changes the behavior to only split if the --- is in it's own line and there are no preceding characters.
Bug Fix
=> MTSRE-1571: Fix YAML document split breaks PEM certs

integration/kubectl-package/fixtures_test.go, integration/kubectl-package/testdata/packages/valid/with_config_no_tests_no_required_properties/README.md, integration/kubectl-package/testdata/packages/valid/with_config_no_tests_no_required_properties/deployment.yaml.gotmpl, integration/kubectl-package/testdata/packages/valid/with_config_no_tests_no_required_properties/external-deployment.yaml.gotmpl, integration/kubectl-package/testdata/packages/valid/with_config_no_tests_no_required_properties/manifest.yaml, integration/kubectl-package/testdata/packages/valid/with_config_no_tests_no_required_properties/namespace.template.yaml.gotmpl, integration/kubectl-package/tree_test.go, internal/cmd/tree.go
`kubectl-package tree` subcommand panics when dealing with a package with all the following characteristics:
- contains a configuration
- its configuration contains **no required** properties
- has no tests associated
This is the panic output:
```
$ kubectl package tree my-package
panic: assignment to entry in nil map
goroutine 1 [running]:
k8s.io/apiextensions-apiserver/pkg/apiserver/schema/defaulting.Default({0x101cfa1e0?, 0x0?}, 0x140004caa50)
/Users/alcosta/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.28.3/pkg/apiserver/schema/defaulting/algorithm.go:46 +0x18c
package-operator.run/internal/packages/packageadmission.AdmitPackageConfiguration({0x101fcaf58, 0x14000671300}, 0x101fab900?, 0x0?, 0x140006061a0, 0x0?)
/Users/alcosta/Work/devel/package-operator/sources/internal/packages/package …
```
=> Fix kubectl-package tree panic with packages with config, no tests and no required props

.github/dependabot.yml
Let dependabot not try to assign labels to PRs because said labels got deleted.
=> Remove labels config from dependabot

integration/package-operator/package_test.go, internal/packages/internal/packageimport/registry.go
Package Operator manager crashes when a `Package` or `ClusterPackage` containing a non existent image reference in the `spec.image` field is created.
Here is an example package that triggers the error:
```
apiVersion: package-operator.run/v1alpha1
kind: Package
metadata:
name: test-unknown-pko
spec:
image: quay.io/package-operator/non-existent:v123
```
Here is the full error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x106c388d4]
goroutine 388 [running]:
package-operator.run/internal/packages/internal/packagetypes.(*RawPackage).DeepCopy(0x0)
/Users/alcosta/Work/devel/package-operator/sources/internal/packages/internal/packagetypes/types.go:61 +0x24 …
```
=> Fix nil pointer dereference on packages with non existent image

internal/controllers/phase_reconciler.go, internal/controllers/phase_reconciler_test.go
Now that PKO is using server-side-apply, we do no longer have to merge existing annotations and labels into our patch, as SSA takes care of keeping them.
This leads to problems with e.g. Cert Manager using annotations and labels to save settings during certificate request and PKO resetting them.
Bug Fix
=> Package Operator should not touch existing meta

internal/packages/internal/packagerender/objects.go, internal/packages/internal/packagerender/objectsettemplate.go, internal/packages/internal/packagerender/objectsettemplate_test.go, internal/packages/internal/packagerender/testdata/base/before.yaml, internal/packages/internal/packagerender/testdata/base/some-statefulset.yaml
This commit changes the ordering of objects within a phase when rendering a Package. Object order is now based on the order within the filesystem.
Files are now traversed in lexical order.
e.g. a.yaml, b.yaml, c/test.yaml, cb.yaml, ...
Objects will retain the order that they are specified in each file encountered.
Bug Fix
=> Base package object order on fs order

internal/packages/internal/packageimport/oci.go, internal/packages/internal/packageimport/oci_test.go, internal/packages/internal/packagetypes/violation.go
It seems like Quay sometimes unexpectedly returns empty images.
Currently, if an empty image is pulled from the registry, the parsing phase completes without errors but then the operator marks the packages as `Invalid` because it can't find the manifest.
This state does not automatically try to re-pull the image, so the package gets stuck there even if the real image in the registry is valid.
With this PR, if an empty image is parsed, an error is immediately returned so that the operator marks the package as `NotReady`.
In this case the logic contains a retry mechanism (with backoff).
Bug Fix
=> Retry image pull on empty image

internal/controllers/objectsetphases/objectsetphase_controller.go, internal/controllers/objectsets/objectset_controller.go, internal/controllers/objecttemplate/objecttemplate_controller.go, internal/preflight/apis_exist.go, internal/preflight/apis_exist_test.go
When creating an ObjectSet including an object that was not registered into the kube-apiserver, the ObjectSet is stuck "Pending" and only when checking PKO logs you see an error:
2023-12-19T10:02:43Z ERROR Reconciler error {"controller": "clusterobjectset", "controllerGroup": "package-operator.run", "controllerKind": "ClusterObjectSet", "ClusterObjectSet":
{"name":"test-6c5fdd6896"}
, "namespace": "", "name": "test-6c5fdd6896", "reconcileID": "486aec14-39d9-4a98-be91-8d056fef2383", "error": "failed to get API group resources: unable to retrieve the complete list of server APIs: operators.coreos.com/v1alpha1: the server could not find the requested resource"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler …
=> fix api resource exists preflight checks

.github/workflows/release.yaml
=> [ci] use redhat-actions/podman-login instead of docker/login-action because cardboard prefers podman

cmd/build/ci.go
because we don't have to cross-compile binaries on downstream CI and we need login + release to be a single command there
=> [cmd/build] add CI:RegistryLoginAndReleaseOnlyImages

integration/package-operator/package_test.go
We suspect GH actions runners are slower now and thus increase the timeouts a little so that our int tests stop failing.
Cherry-picked from @pbabic-redhat's PR branch for #1013 :heart:
=> increase timeout for package integration tests

cmd/build/cluster.go, cmd/build/dev.go, cmd/build/main.go
This PR adds a few cardboard target to create Hypershift local development environment:
```
- Dev:CreateHostedCluster    Create the local Hypershift development environment.
- Dev:InstallHypershiftAPIs  Install the Hypershift HostedCluster API in the local development cluster.
- Dev:LoadCRDs               Load CRDs into the local development cluster.
- Dev:Run                    Run Package Operator manager connected to local development cluster.
```
The dependencies are chained in a way that calling `Dev:CreateHostedCluster` is enough to create everything.
Intermediate targets (`Dev:InstallHypershiftAPIs` and `Dev:LoadCRDs`) are useful for fine-grained setup for specific manual tests.
`Dev:Run` can be used as standalone target to launch PKO locally (outside of the KinD clusters) and …
=> Setup Hypershift development environment

.github/workflows/testing.yaml
=> [ci/testing] do not fail the CI for failed codecov uploads when a fork is tested

integration/package-operator/package_test.go, internal/packages/internal/packagedeploy/chunking.go, internal/packages/internal/packagedeploy/chunking_test.go
This PR adds a chunker that put's at most 1 Megabyte (1 MiB) of objects into a single ObjectSlice and makes PKO behave as described in [1]:
> When using the 'Package' API, Package Operator will automatically split packages that reach a certain limit by using the 'ObjectSlice' API.
The chunker uses next fit binpacking aka:
- keep 1 bucket open
- put objects into the open bucket
- close the bucket and create a new bucket if the next object is too big
Breaking Change
New Feature
[1] https://package-operator.run/docs/concepts/big-packages/
=> [PKO-13] Automatic Big Package Support - add BinpackNextFitChunker

internal/controllers/hostedclusters/hostedcluster_controller.go, internal/controllers/hostedclusters/hostedcluster_controller_test.go
In a previous release, the remote-phase component was moved from the top-level component of its own package to the `remote-phase` component of the package-operator package.
Upgrading all existing remote-phase Packages controlled by PKO includes the (up until now missing pieces):
- diffing existing-package vs desired-package `.spec` and not only `.spec.image`
- updating/overriding `.spec` (and thus also, the crucial field: `.spec.component`) instead of only updating `.spec.image`
Bug Fix
=> PKO-82: Implement regression test and bugfix for invalid remote-phase package upgrade

cmd/build/binary.go
As part of @sclarkso 's work on [PKO-39](https://issues.redhat.com/browse/PKO-39) we discovered, that [check-payload](https://github.com/openshift/check-payload) does not like our go binaries and their validation fails.
Apparently check-payload looks for the existence of a bunch of symbol names [1], which needs the symbol table to be available and not stripped during compilation.
[1] [return types.NewValidationError(types.ErrGoMissingSymbols](https://github.com/openshift/check-payload/blob/5a2d845f8debd082ad27998a34bbe069e5a557d5/internal/validations/validations.go#L84) 
New Feature
Bug Fix
=> [cmd/build] include debug symbols in binaries

cmd/kubectl-package/deps/command.go, cmd/kubectl-package/deps/deps.go, cmd/kubectl-package/kickstartcmd/kickstart.go, internal/cmd/kickstart.go, internal/cmd/kickstart/kickstart.go, internal/cmd/kickstart/kickstart_test.go, internal/cmd/kickstart/phases.go, internal/cmd/kickstart/probing.go, internal/cmd/kickstart/testdata/all-the-objects.yaml, internal/packages/export_kickstart.go, internal/packages/internal/packagekickstart/errors.go, internal/packages/internal/packagekickstart/kickstart.go, internal/packages/internal/packagekickstart/kickstart_test.go, internal/packages/internal/packagekickstart/meta.go, internal/packages/internal/packagekickstart/phases.go, internal/packages/internal/packagekickstart/probing.go, internal/packages/internal/packagekickstart/testdata/errorreporting/duplicate-object.yaml, internal/packages/internal/packagekickstart/testdata/errorreporting/metadata-is-string.yaml, internal/packages/internal/packagekickstart/testdata/errorreporting/missing-apiversion.yaml, internal/packages/internal/packagekickstart/testdata/errorreporting/missing-kind.yaml, internal/packages/internal/packagekickstart/testdata/errorreporting/missing-metadata.yaml, internal/packages/internal/packagekickstart/testdata/errorreporting/missing-name.yaml, internal/packages/internal/packagekickstart/testdata/errorreporting/missing-namespace.yaml, internal/packages/internal/packagekickstart/testdata/errorreporting/same-name-different-namespace.yaml
Introduces the kubectl package kickstart command to quickly start a new package from static kubernetes manifests.
Example:
```
$ kubectl package kickstart olm \                                                   
-f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.28.0/crds.yaml \
-f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.28.0/olm.yaml
Kickstarted the "olm" package with 22 objects.
[WARN] Some kinds don't have availability probes defined:
- OperatorGroup.operators.coreos.com
- CatalogSource.operators.coreos.com
- OLMConfig.operators.coreos.com
$ kubectl package tree olm       
olm
Package namespace/name
└── Phase namespaces
│   ├── /v1, Kind=Namespace /olm
│   ├── /v1, Kind=Namespace /operators
└── Phase …
```
=> Introduce Kickstart command

cmd/build/dev.go
This fix enables me to use `IMAGE_REGISTRY=ctr.erdii.net/pko-dev ./do dev:run`
to move the registry override for quay out of the way so that I can pull existing package images from quay into my development cluster.
I often use this manifest [1] to debug package-operator when developing.
[1]
```yaml
apiVersion: package-operator.run/v1alpha1
kind: Package
metadata:
name: my-nginx
spec:
image: quay.io/erdii-test/nginx-package:e9e4e0e
```
Bug Fix
=> [cmd/build] ./do dev:run: use dynamic registry host in registry-host-overrides flag

cmd/build/generate.go, cmd/package-operator-manager/components/objecttemplate.go, cmd/package-operator-manager/components/options.go, cmd/package-operator-manager/components/options_test.go, config/packages/package-operator/manifest.yaml.tpl, config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl, integration/package-operator/objecttemplate_test.go, internal/controllers/objecttemplate/objecttemplate_controller.go, internal/controllers/objecttemplate/objecttemplate_controller_test.go, internal/controllers/objecttemplate/template_reconciler.go, internal/controllers/objecttemplate/template_reconciler_test.go
https://issues.redhat.com/browse/PKO-49
Currently the object template controller retries with equal hardcoded duration on missing source errors. This can potentially add a considerable amount of API requests to the kube-apiserver as we try to GET the objects using the uncached client. 
This PR makes this retry duration configurable and separates the retry duration for sources which are "optional" and which are not.
Bug Fix
=> make object template controller retry duration on missing sources configurable

config/packages/test-stub-cel/.test-fixtures/cluster-scope/cel-template-cm.yaml, config/packages/test-stub-cel/.test-fixtures/namespace-scope/cel-template-cm.yaml, config/packages/test-stub-cel/cel-template-cm.yaml.gotmpl, integration/package-operator/package_test.go, internal/packages/internal/packagerender/template.go, internal/packages/internal/packagerender/template_test.go
Adds a helper function to go-templates that evaluates CEL expressions. It has access to the full template context and
can utilize reusable CEL expressions.
New Feature
[PKO-69](https://issues.redhat.com/browse/PKO-69)
- Unit tests.
- Local testing:
Added `templated-cm.yaml.gotmpl` to a package:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: templated-cm
annotations:
package-operator.run/phase: deploy
data:
{{if cel "true && false"}}
should-not: "be-here"
{{else}}
banana: "bread"
{{end}}
```
After deploying the package:
```bash
$ kubectl get cm templated-cm -o yaml
apiVersion: v1
data:
banana: bread
kind: ConfigMap
metadata:
name: templated-cm
namespace: default
...
```
=> [PKO-69] Add a go-template CEL Expression Evaluation Function

cmd/package-operator-manager/components/components_test.go
Fixes a unit test. The bug is described in [PKO-160](https://issues.redhat.com/browse/PKO-160)
Bug Fix
=> [PKO-160] Unset KUBECONFIG variable in unit test

cmd/build/package.go, config/packages/.gitignore
Before this change, the build system would output the image tarballs into 
`./config/packages/<packageName>/container.oci.tar` instead of `./cache/packages/<packageName>/container.oci.tar`.
We even needed a special `.gitignore` for them in `./config/packages/`.
This PR cleans up.
To test this, you can run any build command that builds the packages (for example `./do dev:create`) and validate that no `container.oci.tar`balls appear under `./config/packages/...` but in the cache folder instead.
(Dev) Bug Fix
=> fix: store package image tarballs in .cache/packages/<name> instead of the source directory

internal/controllers/mocks_test.go, internal/controllers/phase_reconciler.go, internal/controllers/phase_reconciler_test.go
playing w/ the code-base
Refactor
Do you know if we need the context?
(I see we omit when passing the object at first glance)
=> ref: remove ctx as it's not being used

internal/controllers/objectsetphases/objectsetphase_controller.go, internal/controllers/objectsets/objectset_controller.go, internal/controllers/objecttemplate/objecttemplate_controller.go
This change ensures that all dynamiccache event sources log the same metadata about the object that triggered the event.
```go
c.log.Info(
"processing dynamic cache event",
"gvk", object.GetObjectKind().GroupVersionKind(),
"object", client.ObjectKeyFromObject(object),
"owners", object.GetOwnerReferences(),
)
```
=> ensure uniform logs for "processing dynamic cache event" across controllers

internal/dynamiccache/cache.go, internal/dynamiccache/cache_test.go, internal/dynamiccache/convert.go, internal/dynamiccache/convert_test.go
Since the dynamic cache works with unstructured objects under the hood, it got confused when a program tried to pass a structured api type to `.Watch`, `.Get` or `.List`.
This change implements conversion from structured into unstructured types at incoming boundaries and (if needed) back from unstructured to structured types at outgoing boundaries.
It should explicitly not change any existing behavior of the dynamic cache APIs and thus package-operator as a whole.
=> Implement support for passing structured api types directly to dynamicClient methods.

config/packages/package-operator/components/hosted-cluster/package-operator-manager.Deployment.yaml.gotmpl
Issue link: https://issues.redhat.com/browse/PKO-185
This PR fixes the reference to the configmap that is mounted and expected to contain the trusted ca bundle for the pko instance that runs for a hosted-cluster. 
=> Change trusted-ca-bundle configmap name for hosted-cluster and make the volume mount mandatory

.github/pull_request_template.md
As a part of our sprint retro, the team decided to adopt the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) practice to increase the standard of quality of contributions to the PKO project.
To help with this transition, the PR template should be updated to include a new checkbox that will inform our contributors to follow our contributing practices (i.e., Conventional Commits).
[PKO-196](https://issues.redhat.com/browse/PKO-196)
New Feature
=> [PKO-196] Add Conventional Commits checkbox to the PR template

cmd/build/cluster.go, cmd/build/definitions.go, cmd/build/main.go, cmd/build/test.go, cmd/kubectl-package/repocmd/repo_test.go, config/local-registry.yaml, integration/kubectl-package/repo_test.go
[JIRA Task](https://issues.redhat.com/browse/PKO-169)
* `repo_test.go` was included as unit test but is in fact an integration test because it tries to connect to an external registry (originally `quay.io`).
* the test could produce different results if the user running it was logged or not to `quay.io`.
* Move `repo_test.go` under integration tests.
* Configure `repo_test.go` to use the KinD internal registry (that we already configure) instead of `quay.io`.
* Expand the internal registry configuration adding a proxy that enables authentication, while keeping the old usage intact (`localhost:5001` still points to the plain registry, `localhost:5002` points to the authenticated registry via proxy). This allows to test unauthenticated access.
* `repo_test.go` is written with the standard …
=> [PKO-169] Move repo_test.go to integration tests

.github/dependabot.yml
Jira issue: https://issues.redhat.com/browse/PKO-199
Distribute the workload of reviewing dependency updates
Build/Updates
=> PKO-199 - build(dependabot): assign dependency-maintainers team instead of eqrx

.github/dependabot.yml
Fixes for https://github.com/package-operator/package-operator/pull/1637
I had mistakenly added a wildcard match group to the github-actions update section when I should have added a `k8s.io/*` match group to the root go module section.
Bug Fix
Build/Dependabot
standard.
=> build(dependabot): fix gomod k8s.io dependency PR update grouping

cmd/package-operator-manager/bootstrap/bootstrap.go, cmd/package-operator-manager/components/components.go, cmd/package-operator-manager/components/package.go, internal/packages/export_import.go, internal/packages/internal/packageimport/registry.go, internal/packages/internal/packageimport/request_manager.go, internal/packages/internal/packageimport/request_manager_test.go
having a struct definition for `Registry` in a file called registry.go, which is called like that because it contains a `FromRegistry` function that pulls a package image from an OCI registry (just like oci.go contains a `FromOCI` function!) although that `Registry` struct is actually a facility to deduplicate concurrent pull requests for the same package image.... yeah that confuses my little smoothbrain way too much, so this PR renames the struct to `RequestManager` because it manages (deduplicates) (image pull) requests.
Refactoring
standard.
=> refactor: rename packageimport.Registry to RequestManager

cmd/build/dev.go, cmd/package-operator-manager/components/options.go, config/packages/package-operator/.test-fixtures/no-config/package-operator-manager.Deployment.yaml, config/packages/package-operator/.test-fixtures/openshift-with-proxy/package-operator-manager.Deployment.yaml, config/packages/package-operator/.test-fixtures/root-affinity-tolerations-resources/package-operator-manager.Deployment.yaml, config/packages/package-operator/components/hosted-cluster/.test-fixtures/with-config/package-operator-manager.Deployment.yaml, config/packages/package-operator/components/hosted-cluster/.test-fixtures/without-config/package-operator-manager.Deployment.yaml, config/packages/package-operator/components/hosted-cluster/package-operator-manager.Deployment.yaml.gotmpl, config/packages/package-operator/components/remote-phase/.test-fixtures/affinity-tolerations-resources/package-operator-remote-phase-manager.Deployment.yaml, config/packages/package-operator/components/remote-phase/.test-fixtures/namespace-scope/package-operator-remote-phase-manager.Deployment.yaml, config/packages/package-operator/components/remote-phase/package-operator-remote-phase-manager.Deployment.yaml.gotmpl, config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl, config/remote-phase-static-deployment/deployment.yaml.tpl, config/self-bootstrap-job.yaml.tpl, config/static-deployment/deployment.yaml.tpl
this change enables the manager binaries to discover the serviceaccount they are running under and serves as a stepping stone to later allow package-operator access to the ImagePullSecrets attached to the ServiceAccount
Co-authored-by: Alex Sowitzki <dev@eqrx.net>
https://github.com/package-operator/package-operator/pull/1657 must be merged first
New Feature
Refactoring
standard.
=> Make ServiceAccount available to package-operator pods

cmd/build/test.go, cmd/package-operator-manager/components/package.go, config/local-registry-pullsecret.yaml, go.mod, integration/package-operator/environment.go, integration/package-operator/package_test.go, internal/controllers/packages/unpack_reconciler_test.go, internal/packages/export_import.go, internal/packages/internal/packageimport/kubekeychain/kubekeychain.go, internal/packages/internal/packageimport/kubekeychain/kubekeychain_test.go, internal/packages/internal/packageimport/registry.go, internal/packages/internal/packageimport/request_manager.go, internal/packages/internal/packageimport/request_manager_test.go
Co-authored-by: Alex Sowitzki <dev@eqrx.net>
add support to resolve own ServiceAccount and attached ImagePullSecrets to authenticate package image pull requests made by Package Operator.
I have separated these PRs out and they have to be merged first:
- https://github.com/package-operator/package-operator/pull/1657
- https://github.com/package-operator/package-operator/pull/1658
Documentation PR: https://github.com/package-operator/website/pull/13
New Feature
standard.
=> PKO-183: add support to resolve own ServiceAccount and attached ImagePullSecrets to authenticate package image pull requests 

integration/package-operator/objectset_test.go, integration/package-operator/package_test.go, internal/controllers/phase_reconciler.go, internal/controllers/phase_reconciler_test.go
Update the way to patch the object by removing ownerReference of the teardown external object
This resolves the https://issues.redhat.com/browse/PKO-60
This PR replaces https://github.com/package-operator/package-operator/pull/1382
Bug Fix
standard.
=> [PKO-60] Do not attempt to overwrite full object on teardown of object which we don't control anymore

.github/dependabot.yml
Similar to https://github.com/package-operator/package-operator/pull/1744 this pr ensures that the golang.org/x modules get bumped together, since they tend to have interdependencies.
Example PR: https://github.com/package-operator/package-operator/pull/1748
Bug Fix
standard.
=> group dependabot prs for golangx

.github/dependabot.yml
This PR reduces a small amount of toil since a single bump to cardboard currently opens 4 separate PRs:
- https://github.com/package-operator/package-operator/pull/1740
- https://github.com/package-operator/package-operator/pull/1741
- https://github.com/package-operator/package-operator/pull/1742
- https://github.com/package-operator/package-operator/pull/1743
Bug Fix
standard.
=> fix(dependabot): group cardboard upgrade PRs

.github/workflows/testing.yaml
This is to resolve https://issues.redhat.com/browse/PKO-208 for adding a github action to run go mod tidy to keep the module clean
Bug Fix 
standard.
=> [PKO-208]Add GH Action that runs go mod tidy on dependabot PRs

.github/workflows/testing.yaml
This reverts commit d1edcee25b11908d9ef3c8da6f614f8ad2cfa9a0.
Does not work since the PR creates an additonal job that creates new commits. The existing job never sees them though since they run in parallel.
=> Revert "[PKO-208]Add GH Action that runs go mod tidy on dependabot PRs (#1768)

cmd/build/definitions.go
I got fed up forgetting to use `IMAGE_REGISTRY=foo.bar.dev ./do dev:...` when creating my local dev env and then having to re-create it just to be able to deploy a dev package image from quay.io, hence I propose:
Let's stop shadowing the real quay.io in our dev environments.
Bug Fix
standard.
=> chore(cmd/build): change default dev registry address to free up access to quay

internal/metrics/recorder.go, internal/metrics/recorder_test.go
Add the currently active image to the availability metric to give users the ability to correlate the status to a specific version.
Issue Link: https://issues.redhat.com/browse/PKO-251
New Feature
standard.
=> Add image label to pkg availability metric

cmd/build/dev.go
Remove govulncheck execution from the precommit run. Devs sometimes have outdated go versions which causes alerts to pop up that are specific to the developer, not our deployment.
Docs/Test
standard.
=> [PKO-231] Remove govulncheck from precommit

.github/dependabot.yml
This is an alertnative solution for dependabot to run go mod tidy with all modules and group them with a single PR.
To resolve https://issues.redhat.com/browse/PKO-208
New Feature
standard.
This is the test https://github.com/weherdh/package-operator/pulls from my forked repo
=> Update dependabot.yml to group modules for dependencies update

.github/workflows/testing.yaml
This is to resolve PKO-254, to add a new job for dependabot only to run `go work sync` and `go mod tidy`
New Feature
standard.
This PR need the PAT token first to allow the github-action bot to merge and sync the dependencies and report the CI status. Pls check PKO-255
=> [PKO-254]Enable go work sync for dependabot

.github/workflows/testing.yaml
=> fix: add write permissions to update-go-modules job

.github/workflows/testing.yaml
because
https://github.com/actions/checkout#push-a-commit-to-a-pr-using-the-built-in-token
says so
=> fix(testing/update-go-modules): drop fetch-depth from checkout action

.github/workflows/testing.yaml
Co-Authored-By: Alex Sowitzki <asowitzk@redhat.com>
=> fix(testing/update-go-modules): re-export the token as GITHUB_TOKEN

.github/workflows/testing.yaml
- **fix(testing/update-go-modules): re-export the token as GITHUB_TOKEN**
- **fix(testing/update-go-modules): try pushing to an inline ref again**
=> pattoken.v8

cmd/build/generate.go, cmd/package-operator-manager/bootstrap/bootstrap.go, cmd/package-operator-manager/bootstrap/init.go, cmd/package-operator-manager/bootstrap/init_test.go, cmd/package-operator-manager/components/options.go, cmd/package-operator-manager/components/package.go, cmd/package-operator-manager/components/package_test.go, config/packages/package-operator/components/hosted-cluster/manifest.yaml.tpl, config/packages/package-operator/components/hosted-cluster/package-operator-hosted-cluster-manager.Deployment.yaml.gotmpl, config/packages/package-operator/manifest.yaml.tpl, config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl, config/self-bootstrap-job.yaml.tpl, internal/controllers/packages/package_controller.go, internal/controllers/packages/package_controller_test.go, internal/controllers/packages/unpack_reconciler.go, internal/controllers/packages/unpack_reconciler_test.go, internal/imageprefix/imageprefix.go, internal/imageprefix/imageprefix_test.go, internal/packages/internal/packagedeploy/deployer.go, internal/packages/internal/packagedeploy/deployer_test.go, internal/packages/internal/packageimport/request_manager.go, internal/packages/internal/packageimport/request_manager_test.go
This PR implements global image prefix overrides.
You can apply them by passing them in a `PKO_IMAGE_PREFIX_OVERRIDES` env var or in `image-prefix-overrides` flag in `from=to` format, eg. `quay.io/my-org/=mirror.example.com/mirror-org/`
Jira: [PKO-237](https://issues.redhat.com/browse/PKO-237)
This PR does not contain integration tests and must be manually tested before merging. 
More information in [PKO-264](https://issues.redhat.com/browse/PKO-264)
New Feature
standard.
=> Image prefix overrides

cmd/build/ci.go, cmd/build/dev.go, cmd/build/lint.go
Currently the job runs go mod tidy in the submodules.
If git diff reports that the repo is dirty, the pipeline fails. Currently the git diff output is called with the "–quiet" flag which makes debugging hard. Remove flag and tidy up code.
Bug Fix
standard.
=> [PKO-245] Sanitize code

internal/adapters/objecttemplate.go, internal/adapters/objecttemplate_test.go, internal/autoimpersonation/ownership/ownership_test.go, internal/controllers/objecttemplate/objecttemplate_controller.go, internal/controllers/objecttemplate/template_reconciler.go, internal/controllers/objecttemplate/template_reconciler_test.go
This PR  the ObjectTemplate adapter (`genericObjectTemplate`) interface and implementation from the `internal/controllers/objecttemplate` package to the `internal/adapters` package.
[PKO-267](https://issues.redhat.com/browse/PKO-267)
standard.
=> [PKO-267] Move ObjectTemplate adapter into adapters package

cmd/build/binary.go, cmd/build/ci.go, cmd/build/image.go, cmd/build/main.go
Exposes the binary compilation logic to enable building `kubectl-package` in a Containerfile.
Usage:
```
./do CI:Compile kubectl-package linux amd64
```
Jira: [PKO-263](https://issues.redhat.com/browse/PKO-263)
New Feature
standard.
=> [PKO-263] Expose cardboard compile logic

cmd/package-operator-manager/main.go, cmd/remote-phase-manager/main.go
This is to resolve https://issues.redhat.com/browse/PKO-242. For binaries
package-operator
remote-phase-manager
to reduce the log level to Error by default and make it optional 
New Feature
standard.
Test results for reducing the log level:
```
I0314 14:35:20.111683   34531 leaderelection.go:257] attempting to acquire leader lease package-operator-system/8a4hp84a6s.package-operator-lock...
I0314 14:36:11.106208   34531 leaderelection.go:271] successfully acquired lease package-operator-system/8a4hp84a6s.package-operator-lock
{"level":"error","ts":"2025-03-14T14:36:32+11:00","msg":"Reconciler error","controller":"clusterobjectset","controllerGroup":"package-operator.run","controllerKind":"ClusterObjectSet","ClusterObjectSet":{"name":"package-operator-8f5f9d9b4"},"namespace":"","name":"packa …
```
=> [PKO-242]Reduce loglevel to ERROR by default

internal/controllers/objecttemplate/template_reconciler.go
this was causing issues with Packages owned by ObjectTemplates because there was a hot-loop to add and remove the metrics finalizer that was recently added in https://github.com/package-operator/package-operator/pull/1927
Co-Authored-By: Petr Babic <pbabic@redhat.com>
standard.
=> fix(ObjectTemplate controller): copy finalizers from existing templated object to prevent removing them

integration/package-operator/objectset_test.go, internal/controllers/objectsets/revision_reconciler.go, internal/controllers/objectsets/revision_reconciler_test.go
**Bug:** If an ObjectSet had an outdated list of previous revisions (e.g., includes deleted revisions),
the ObjectSet controller would error when trying to get a non-existing previous revision.
The fix is to ignore non-existing previous revisions.
Jira: [PKO-293](https://issues.redhat.com/browse/PKO-293)
Bug Fix
standard.
=> [PKO-293] Fix: Ignore NotFound error when getting previous revisions

apis/core/v1alpha1/clusterobjectset_types.go, apis/core/v1alpha1/objectset_types.go, cmd/kubectl-package/rolloutcmd/history_test.go, config/crds/package-operator.run_clusterobjectsets.yaml, config/crds/package-operator.run_objectsets.yaml, config/static-deployment/1-package-operator.run_clusterobjectsets.yaml, config/static-deployment/1-package-operator.run_objectsets.yaml, docs/api-reference.md, integration/package-operator/objectdeployment_test.go, integration/package-operator/objectset_test.go, internal/adapters/objectset.go, internal/adapters/objectset_test.go, internal/cmd/client_test.go, internal/controllers/objectdeployments/new_revision_reconciler.go, internal/controllers/objectdeployments/new_revision_reconciler_test.go, internal/controllers/objectdeployments/objectset_reconciler_test.go, internal/controllers/objectsets/revision_reconciler.go, internal/controllers/objectsets/revision_reconciler_test.go, internal/testutil/adaptermocks/objectset_mock.go
Add revision assignment logic to the NewRevisionReconciler in the ObjectDeployment controller:
* Add an immutable `.spec.revision` field to the (Cluster)ObjectSet API.
* Assign `.spec.revision` to new revisions as they're created by the NewRevisionReconciler (in the ObjectDeployment controller).
* `.spec.revision` is computed from the previous revisions as `latestRevision + 1` (or `1` if no previous).
* The RevisionReconciler (in the ObjectSet controller) assigns `.status.revision` based on `.spec.revision` (if present).
Implements the first part of [PKO-297](https://issues.redhat.com/browse/PKO-297). The revision assignment logic in the ObjectSet controller will be removed in a follow-up ticket.
New Feature
standard.
=> [PKO-297] Assign ObjectSet revision number in the ObjectDeployment controller
